# Site settings
title: Leah Velleman
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.velleman.org" # the base hostname & protocol for your site
twitter_username: leahvelleman
github_username: leahvelleman

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  syntax_highlighter: coderay

image:
  source: assets/images/_fullsize
  presets:
    score:
      width: 900

lilypond:
  foo: bar

host: 127.0.0.1
